version: "3.9"
services:
  flint.example:
    # - when developing use local builds
    # build: .
    # - or deploy using our CI
    image: ghcr.io/moja-global/rest_api_flint.example:master
    container_name: flint.example
    ports:
      - "8080:8080"
    volumes:
      - .:/app
